spring:
  application:
    name: apigateway
  cloud:
    gateway: 
      routes:
        - id: loginservice
          uri: http://localhost:8081
          predicates:
            - Path=/api/user/**
        
        - id: profileservice
          uri: http://localhost:8082
          predicates:
            - Path=/api/profile/**
            
        - id: productservice
          uri: http://localhost:8083
          predicates:
            - Path=/api/pro/**
server:
  port: 9000
debug: true # Add this line to enable debug mode
