version: '3'
services:
  mongo:
    image: mongo
    container_name: mongodb-container1
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network
  springboot-app:
    image: springboot-mongo:latest
    build: .
    ports:
      - "8089:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/vehicles_db
    networks:
      - mongo-network
volumes:
  mongo-data:
networks:
  mongo-network:
    driver: bridge
